# Wikibase for testing
version: '3'

services:
  wikibase:
    image: "${WIKIBASE_IMAGE_NAME}:latest"
    links:
      - mysql
    volumes:
      - mediawiki-images-data:/var/www/html/images
    depends_on:
    - mysql
    restart: unless-stopped
    networks:
      default:
        aliases:
         - wikibase.svc
         # CONFIG - Add your real wikibase hostname here, only for internal names and when NOT terminating SSL outside the container.
    environment:
      - DB_SERVER=mysql.svc:3306
      # CONFIG - Change the default values below
      - MW_ADMIN_NAME=WikibaseAdmin
      - MW_ADMIN_PASS=WikibaseDockerAdminPass
      - MW_ADMIN_EMAIL=admin@example.com
      - MW_WG_SECRET_KEY=secretkey
      # CONFIG - Change the default values below (should match mysql values in this file)
      - DB_USER=wikiuser
      - DB_PASS=sqlpass
      - DB_NAME=my_wiki
  mysql:
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - mediawiki-mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: 'my_wiki'
      MYSQL_USER: 'wikiuser'
      MYSQL_PASSWORD: 'sqlpass'
    networks:
      default:
        aliases:
         - mysql.svc
  wdqs-frontend:
    image: "${QUERYSERVICE_UI_IMAGE_NAME}:latest"
    restart: unless-stopped
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs.svc
  wdqs:
    image: "${QUERYSERVICE_IMAGE_NAME}:latest"
    restart: unless-stopped
    volumes:
      - query-service-data:/wdqs/data
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST=wikibase.svc
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
    expose:
      - 9999
  wdqs-updater:
    image: "${QUERYSERVICE_IMAGE_NAME}:latest"
    restart: unless-stopped
    command: /runUpdate.sh
    depends_on:
    - wdqs
    - wikibase
    networks:
      default:
        aliases:
         - wdqs-updater.svc
    environment:
     - WIKIBASE_HOST=wikibase.svc
     - WDQS_HOST=wdqs.svc
     - WDQS_PORT=9999

volumes:
  mediawiki-mysql-data:
  mediawiki-images-data:
  query-service-data:
