name: Build and test Wikibase and friends

on:
  push:

env:
  DOCKER_CACHE_VERSION: 0
  WIKIBASE_IMAGE_NAME: wikibase
  MEDIAWIKI_IMAGE_VERSION: 1.35
  QUERYSERVICE_IMAGE_NAME: wdqs
  QUERYSERVICE_VERSION: 0.3.55
  QUERYSERVICE_UI_IMAGE_NAME: wdqs-ui
  QUERYSERVICE_UI_COMMIT_HASH: e84ab35125557ff073f42ba522a684d35c288b38

jobs:
  build_wikibase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
        with:
          key: wikibase-docker-cache-${{env.DOCKER_CACHE_VERSION}}-{hash}
          restore-keys: wikibase-docker-cache-${{env.DOCKER_CACHE_VERSION}}-

      - name: Cache git_cache repos
        uses: actions/cache@v2
        env:
          cache-name: cache-wikibase-git-repo
        with:
          path: git_cache
          key: cache-wikibase-git-repo

      - name: Build Tarball
        run: bash build_github.sh wikibase

      - name: Archive tar production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wikibase Tarball
          path: artifacts/Wikibase.tar.gz #${{env.TARBALL_PATH}}

      - name: Archive docker production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wikibase Docker Image
          path: artifacts/wikibase.docker.tar.gz

  build_queryservice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
        with:
          key: queryservice-docker-cache-${{env.DOCKER_CACHE_VERSION}}-{hash}
          restore-keys: queryservice-docker-cache-${{env.DOCKER_CACHE_VERSION}}-

      - name: Build QueryService Image 
        id: download_step
        run: bash build_github.sh queryservice

      # - name: Archive tar production artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: QueryService Tarball
      #     path: #${{env.TARBALL_PATH}}

      - name: Archive docker production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: QueryService Docker Image
          path: artifacts/wdqs.docker.tar.gz

  build_queryservice_ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
        with:
          key: ui-docker-cache-${{env.DOCKER_CACHE_VERSION}}-{hash}
          restore-keys: ui-docker-cache-${{env.DOCKER_CACHE_VERSION}}-

      - name: Build QueryService UI
        run: bash build_github.sh queryservice-ui

      - name: Archive tar production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: QueryService UI Tarball
          path: artifacts/wdqs-ui.tar.gz #${{env.TARBALL_PATH}}

      - name: Archive docker production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: QueryService UI Docker Image
          path: wdqs-ui.docker.tar.gz

  test_wikibase:
    needs:
      - build_wikibase
      - build_queryservice
      - build_queryservice_ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Wikibase docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: Wikibase Docker Image

      - name: Get QueryService docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: QueryService Docker Image

      - name: Get QueryService UI docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: QueryService UI Docker Image

      - name: Run Docker Tests
        run: bash test_scripts/test_docker.sh

      - name: Archive docker test artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test artifacts
          path: |
            test_scripts/selenium/log
            test_scripts/log
