name: Build Wikibase

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, queryservice-wip ]
  pull_request:
    branches: [ main ]

env:
  WIKIBASE_IMAGE_NAME: wikibase

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Cache git_cache repos
        uses: actions/cache@v2
        env:
          cache-name: cache-git-repos
        with:
          path: git_cache
          key: cache-git-repos

      - name: Cache quibble cache
        uses: actions/cache@v2
        env:
          cache-name: cache-quibble-cache
        with:
          path: cache
          key: ${{ runner.os }}-cache-quibble-cache

      - name: Update the git cache
        run: bash update_cache.sh

      - name: Build Tarball
        run: bash build_scripts/build_wikibase.sh

      - name: Archive tar production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wikibase Tarball
          path: Wikibase.tar.gz

      - name: Build Docker image
        run: bash build_scripts/build_wikibase_docker.sh wikibase

      - name: Archive docker production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wikibase Docker Image
          path: wikibase.docker.tar.gz
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get docker artifact
        uses: actions/download-artifact@v2
        with:
          name: Wikibase Docker Image
      - name: Run Docker Tests
        run: bash test_docker.sh
