name: Build QueryService UI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ queryservice-ui ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: wdqs-ui
  COMMIT_HASH: e84ab35125557ff073f42ba522a684d35c288b38
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build QueryService UI Tarball
        id: download_step
        run: bash build_scripts/build_queryservice_ui.sh

      - name: Archive tar production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: QueryService UI Tarball
          path: ${{env.TARBALL_PATH}}

      - name: Build Docker image
        run: bash build_scripts/build_queryservice_ui_docker.sh ${{env.IMAGE_NAME}}

      - name: Archive docker production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: QueryService UI Docker Image
          path: wdqs-ui.docker.tar.gz
